project:
  type: website
  output-dir: _site

format:
  html:
    toc: true
    toc-depth: 4
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: references

    theme: 
      light: [ pulse,  "formatting/common.scss", "formatting/light.scss" ]
      dark:  [ pulse,  "formatting/common.scss", "formatting/dark.scss"  ]
    header-includes: |
      <meta name="theme-color" content="#054c2b"/>

website:
  title: '<code style="color: white; background-color: #054c2b;">aperiodic.dev</code>'
  image: "/images/orbits.webp"
  favicon: "/images/profile.webp"
  description: Posts about open-source scientific software, alongside a personal portfolio!

  twitter-card: true
  open-graph: true

  site-url: https://aperiodic.dev
  repo-url: https://github.com/cadojo/aperiodic
  repo-actions: [edit, issue]
  search:
    type: textbox
  page-navigation: true
  page-footer:
    left: "__Copyright © 2022 Joe Carpinelli__"
    center:
      - text: "License"
        href: permission/index.qmd
      - text: "Credits"
        href: credits/index.md
      - text: "Privacy"
        href: privacy/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/code_typed
        aria-label: Twitter
      - icon: github
        href: https://github.com/cadojo
        aria-label: GitHub

  navbar:
    collapse: true
    background: primary
    left:
      - text: "Portfolio"
        file: portfolio/background/introduction/index.md
      - text: "Blog"
        file: blog/index.md
        
  sidebar:
    - id: portfolio
      contents:
        - section: "Background"
          contents:
            - portfolio/background/introduction/index.md
            - portfolio/background/education/index.md
        - section: "Communication"
          contents:
            - portfolio/communication/publications/index.md
            - portfolio/communication/presentations/index.md
        - section: "Software"
          contents:
            - portfolio/software/scientific/index.md
            - portfolio/software/miscellaneous/index.qmd
